---

- name: test and reload apache2
  command: apache2ctl configtest
  notify: reload apache2

- name: test and restart apache2
  command: apache2ctl configtest
  notify: restart apache2

- name: reload apache2
  service:
    name: apache2
    state: reloaded

- name: restart apache2
  service:
    name: apache2
    state: restarted
  notify:
    - restart php-fpm


- name: restart nextcloud-notify-push
  service:
    name: nextcloud-notify-push
    state: restarted

- name: restart php-fpm
  service:
    name: "php{{ nextcloud_php_version }}-fpm"
    state: restarted
  when: __nextcloud_php_fpm_bin and __nextcloud_php_fpm_bin.stat.exists
