---
scenario:
  name: default
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: nextcloud-buster64
    box: debian/buster64
provisioner:
  name: ansible
  side_effect: side_effect.yml
  lint:
    name: ansible-lint
    enabled: False
verifier:
  name: testinfra
  lint:
    name: flake8
