---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: nextcloud-bullseye64
    box: debian/bullseye64
  - name: nextcloud-buster64
    box: debian/buster64
lint: |
  set -e
  yamllint .
#  ansible-lint
