---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: buster64
    box: debian/buster64
  - name: stretch64
    box: debian/stretch64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False
verifier:
  name: testinfra
  lint:
    name: flake8
