---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: systemli.mariadb
    - role: ansible-role-nextcloud
  vars:
    nextcloud_apache_php: False
    nextcloud_admin_password: topsecret
    nextcloud_mysql_password: topsecret
    nextcloud_version: "{{ '19.0.4' if ansible_distribution_release == 'buster' else '15.0.14' }}"
